export const styles = {
  page: {
    minHeight: "100vh",
    background: "#1C1210",
    backgroundImage: "radial-gradient(circle at 50% 0%, rgba(201,162,75,0.06), transparent 60%)",
    color: "#F1E7D0",
    fontFamily: "'Space Mono', monospace",
    padding: "0 0 60px",
  },
  marquee: {
    position: "relative",
    textAlign: "center",
    padding: "34px 20px 22px",
    borderBottom: "1px solid rgba(201,162,75,0.25)",
    overflow: "hidden",
  },
  marqueeBulbs: {
    display: "flex",
    justifyContent: "center",
    gap: 10,
    marginBottom: 18,
    flexWrap: "wrap",
    padding: "0 10px",
  },
  bulb: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#C9A24B",
    display: "inline-block",
    animation: "flicker 1.8s infinite ease-in-out",
  },
  marqueeInner: { display: "flex", alignItems: "center", justifyContent: "center", gap: 14 },
  marqueeTitle: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: "clamp(32px, 6vw, 52px)",
    letterSpacing: "0.12em",
    margin: 0,
    color: "#F1E7D0",
    textShadow: "0 0 18px rgba(201,162,75,0.35)",
  },
  marqueeSub: {
    fontFamily: "'Libre Baskerville', serif",
    fontStyle: "italic",
    color: "#8B7355",
    fontSize: 13,
    marginTop: 10,
  },
  controls: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    padding: "24px 20px 0",
    maxWidth: 1100,
    margin: "0 auto",
  },
  searchWrap: { position: "relative", flex: "1 1 220px" },
  searchInput: {
    width: "100%",
    background: "#241815",
    border: "1px solid rgba(201,162,75,0.3)",
    borderRadius: 4,
    padding: "10px 12px 10px 34px",
    color: "#F1E7D0",
    fontFamily: "'Space Mono', monospace",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
  },
  select: {
    background: "#241815",
    border: "1px solid rgba(201,162,75,0.3)",
    borderRadius: 4,
    padding: "10px 12px",
    color: "#F1E7D0",
    fontFamily: "'Space Mono', monospace",
    fontSize: 13,
    outline: "none",
  },
  favToggle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    border: "1px solid rgba(201,162,75,0.3)",
    borderRadius: 4,
    padding: "10px 14px",
    color: "#C9A24B",
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  favToggleActive: { background: "#C9A24B", color: "#1C1210", borderColor: "#C9A24B" },
  chipRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    padding: "16px 20px 0",
    maxWidth: 1100,
    margin: "0 auto",
  },
  chip: {
    background: "transparent",
    border: "1px solid rgba(241,231,208,0.18)",
    color: "#C9BBA0",
    borderRadius: 20,
    padding: "6px 14px",
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    cursor: "pointer",
  },
  chipActive: { background: "#5C1A24", borderColor: "#5C1A24", color: "#F1E7D0" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(190px, 1fr))",
    gap: 22,
    padding: "28px 20px 0",
    maxWidth: 1100,
    margin: "0 auto",
  },
  card: { cursor: "pointer" },
  poster: {
    position: "relative",
    aspectRatio: "2 / 3",
    borderRadius: 6,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid rgba(201,162,75,0.2)",
  },
  sprocketsTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 10,
    backgroundImage: "repeating-linear-gradient(90deg, rgba(28,18,16,0.85) 0 6px, transparent 6px 14px)",
    backgroundColor: "rgba(28,18,16,0.4)",
  },
  sprocketsBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 10,
    backgroundImage: "repeating-linear-gradient(90deg, rgba(28,18,16,0.85) 0 6px, transparent 6px 14px)",
    backgroundColor: "rgba(28,18,16,0.4)",
  },
  posterInitial: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 64,
    color: "rgba(241,231,208,0.22)",
  },
  starBtn: {
    position: "absolute",
    top: 16,
    right: 8,
    background: "rgba(28,18,16,0.55)",
    border: "none",
    borderRadius: "50%",
    width: 28,
    height: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  cardFooter: { padding: "10px 2px 0" },
  cardTitle: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 20,
    letterSpacing: "0.02em",
    margin: 0,
    color: "#F1E7D0",
  },
  cardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "#8B7355",
    marginTop: 4,
    flexWrap: "wrap",
  },
  dot: { opacity: 0.6 },
  ratingBadge: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 3,
    background: "#C9A24B",
    color: "#1C1210",
    borderRadius: 3,
    padding: "1px 6px",
    fontWeight: 700,
  },
  empty: { textAlign: "center", padding: "60px 20px" },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(10,6,5,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    zIndex: 50,
  },
  ticket: {
    display: "flex",
    background: "#F1E7D0",
    color: "#1C1210",
    borderRadius: 10,
    maxWidth: 640,
    width: "100%",
    maxHeight: "85vh",
    overflowY: "auto",
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
  },
  ticketMain: { flex: 1, padding: "28px 26px", position: "relative" },
  closeBtn: {
    position: "absolute",
    top: 14,
    right: 14,
    background: "#1C1210",
    border: "none",
    borderRadius: "50%",
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  ticketEyebrow: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.1em",
    color: "#8B4A52",
    margin: 0,
  },
  ticketTitle: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 40,
    margin: "4px 0 12px",
    color: "#1C1210",
  },
  ticketSynopsis: {
    fontFamily: "'Libre Baskerville', serif",
    fontSize: 14,
    lineHeight: 1.6,
    color: "#3A2A1C",
    marginBottom: 20,
  },
  detailGrid: { display: "flex", flexDirection: "column", gap: 8 },
  detailRow: { display: "flex", alignItems: "baseline", fontSize: 12, fontFamily: "'Space Mono', monospace" },
  detailLabel: { color: "#8B4A52", whiteSpace: "nowrap", textTransform: "uppercase", letterSpacing: "0.06em" },
  detailDots: { flex: 1, borderBottom: "1px dotted rgba(28,18,16,0.3)", margin: "0 8px", transform: "translateY(-3px)" },
  detailValue: { color: "#1C1210", textAlign: "right" },
  perforation: { width: 0, borderLeft: "2px dashed rgba(28,18,16,0.25)", margin: "16px 0" },
  ticketStub: {
    width: 130,
    flexShrink: 0,
    background: "#E5D6B0",
    padding: "26px 14px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    gap: 4,
    borderRadius: "0 10px 10px 0",
  },
  stubLabel: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 10,
    letterSpacing: "0.1em",
    color: "#8B4A52",
    marginTop: 10,
  },
  stubRating: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 30, margin: 0, color: "#1C1210" },
  stubSeat: { fontFamily: "'Bebas Neue', sans-serif", fontSize: 22, margin: 0, color: "#1C1210" },
  stubBtn: {
    marginTop: 16,
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: "transparent",
    border: "1px solid #1C1210",
    borderRadius: 20,
    padding: "7px 10px",
    fontSize: 10,
    fontFamily: "'Space Mono', monospace",
    cursor: "pointer",
    color: "#1C1210",
  },
  stubBtnActive: { background: "#1C1210", color: "#F1E7D0" },

  // --- CRUD additions -------------------------------------------------
  addBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#C9A24B",
    border: "1px solid #C9A24B",
    borderRadius: 4,
    padding: "10px 14px",
    color: "#1C1210",
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  cardIconRow: {
    position: "absolute",
    top: 16,
    left: 8,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    zIndex: 2,
  },
  cardIconBtn: {
    background: "rgba(28,18,16,0.55)",
    border: "none",
    borderRadius: "50%",
    width: 26,
    height: 26,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  stubIconRow: { display: "flex", gap: 8, marginTop: 14 },
  stubIconBtn: {
    background: "transparent",
    border: "1px solid #1C1210",
    borderRadius: "50%",
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#1C1210",
  },
  formOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(10,6,5,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    zIndex: 60,
  },
  formCard: {
    background: "#F1E7D0",
    color: "#1C1210",
    borderRadius: 10,
    maxWidth: 480,
    width: "100%",
    maxHeight: "85vh",
    overflowY: "auto",
    padding: "26px 26px 22px",
    position: "relative",
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
  },
  formTitle: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 30,
    margin: "0 0 18px",
    color: "#1C1210",
    letterSpacing: "0.02em",
  },
  formGrid: { display: "flex", flexDirection: "column", gap: 14 },
  formRow2: { display: "flex", gap: 12 },
  formField: { flex: 1, display: "flex", flexDirection: "column", gap: 4 },
  formLabel: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "#8B4A52",
  },
  formInput: {
    background: "#fff",
    border: "1px solid rgba(28,18,16,0.25)",
    borderRadius: 4,
    padding: "8px 10px",
    fontFamily: "'Space Mono', monospace",
    fontSize: 13,
    color: "#1C1210",
    outline: "none",
  },
  formTextarea: {
    background: "#fff",
    border: "1px solid rgba(28,18,16,0.25)",
    borderRadius: 4,
    padding: "8px 10px",
    fontFamily: "'Libre Baskerville', serif",
    fontSize: 13,
    color: "#1C1210",
    outline: "none",
    resize: "vertical",
    minHeight: 64,
  },
  formError: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    color: "#A32D2D",
    margin: "2px 0 0",
  },
  formActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 22,
  },
  formCancelBtn: {
    background: "transparent",
    border: "1px solid rgba(28,18,16,0.3)",
    borderRadius: 4,
    padding: "9px 16px",
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    cursor: "pointer",
    color: "#1C1210",
  },
  formSubmitBtn: {
    background: "#1C1210",
    border: "1px solid #1C1210",
    borderRadius: 4,
    padding: "9px 16px",
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    color: "#F1E7D0",
  },

  // --- Auth additions ---------------------------------------------------
  authBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    flexWrap: "wrap",
    padding: "14px 20px 0",
    maxWidth: 1100,
    margin: "0 auto",
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
  },
  authBadge: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: "#C9A24B",
  },
  authBadgeMuted: {
    color: "#8B7355",
  },
  authBarBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    border: "1px solid rgba(201,162,75,0.35)",
    borderRadius: 20,
    padding: "6px 12px",
    color: "#F1E7D0",
    fontFamily: "'Space Mono', monospace",
    fontSize: 11,
    cursor: "pointer",
  },
  authTabs: {
    display: "flex",
    gap: 6,
    marginBottom: 18,
  },
  authTab: {
    flex: 1,
    background: "transparent",
    border: "1px solid rgba(28,18,16,0.25)",
    borderRadius: 4,
    padding: "8px 0",
    fontFamily: "'Space Mono', monospace",
    fontSize: 12,
    cursor: "pointer",
    color: "#1C1210",
  },
  authTabActive: { background: "#1C1210", color: "#F1E7D0", borderColor: "#1C1210" },
  authDisclaimer: {
    fontFamily: "'Space Mono', monospace",
    fontSize: 10,
    color: "#8B4A52",
    marginTop: 16,
    textAlign: "center",
    lineHeight: 1.5,
  },
};
